
# This script is designed to evaluate possible errors in the measurement. 

# In order to run the script, put the suspected error trials in a map, set the working directory and run this code. 


### Function to draw ellipse

```{r}
draw.ellipse<-function(x,y,a=1,b=1,angle=0,segment=NULL,arc.only=TRUE, 
                       deg=TRUE,nv=100,border=NULL,col=NA,lty=1,lwd=1,...) {
  
  if(is.null(segment)) {
    # set segment to full ellipse if not supplied
    if(deg) segment<-c(0,360)
    else segment<-c(0,2*pi)
  }
  ## workhorse internal function draw ellipse
  draw1ellipse <-
    function(x, y, a = 1, b = 1, angle = 0, segment=NULL, 
             arc.only=TRUE, nv = 100, deg = TRUE, border=NULL, col=NA, lty=1, lwd=1, ...)
    {
      # if input is in degrees
      if (deg) {
        angle <- angle * pi/180
        segment <- segment * pi/180
      }
      z <- seq(segment[1], segment[2], length = nv + 1)
      xx <- a * cos(z)
      yy <- b * sin(z)
      alpha <- xyangle(xx, yy, directed = TRUE, deg = FALSE)
      rad <- sqrt(xx^2 + yy^2)
      xp <- rad * cos(alpha + angle) + x
      yp <- rad * sin(alpha + angle) + y
      if (!arc.only) {
        xp <- c(x, xp, x)
        yp <- c(y, yp, y)
      }
      polygon(xp, yp, border=border, col=col, lty=lty, lwd=lwd, ...)
      invisible(NULL)
    }
  ## internal function for the internal function
  xyangle <-
    function(x, y, directed = FALSE, deg = TRUE)
    {
      if (missing(y)) {
        y <- x[,2]
        x <- x[,1]
      }
      out <- atan2(y, x)
      if (!directed)
        out <- out %% pi   
      if (deg) # if output is desired in degrees
        out <- out * 180 / pi
      out
    }
  if (missing(y)) {
    y <- x[,2]
    x <- x[,1]
  }
  n <- length(x)
  if (length(a) < n)
    a <- rep(a, n)[1:n]
  if (length(b) < n)
    b <- rep(b, n)[1:n]
  if (length(angle) < n)
    angle <- rep(angle, n)[1:n]
  if (length(col) < n)
    col <- rep(col, n)[1:n]
  if (length(border) < n)
    border <- rep(border, n)[1:n]
  if (length(nv) < n)
    nv <- rep(nv, n)[1:n]
  if(n==1)
    draw1ellipse(x,y,a,b,angle=angle,segment=segment,
                 arc.only=arc.only,deg=deg,nv=nv,col=col,border=border,
                 lty=lty,lwd=lwd,...)
  else {
    if (length(segment) < 2*n)
      segment <- matrix(rep(segment,n), n, 2, byrow=TRUE)
    lapply(1:n, function(i) draw1ellipse(x[i], y[i], a[i], b[i], 
                                         angle=angle[i], segment=segment[i,], arc.only=arc.only, deg=deg, 
                                         nv=nv[i], col=col[i], border=border[i],
                                         lty=lty, lwd=lwd, ...))
  }
  invisible(NULL)
}

```


# visualizatioon

```{r}

setwd("C:\\Research data\\Postural_Control_Github\\scripts\\Check_Raw_Files")

  raw <- read.table("VP251_screening_sr_31_5.dat",  skip=4, sep="")
  raw <- raw[,c(8,9)]

"VP251_screening_sr_31_5.dat"

ALLESFUNCTIE <- function
(.file){

  
  #reading in data
  raw <- read.table(.file,  skip=4, sep="")
  raw <- raw[,c(8,9)]
  name <- .file
  
  colnames(raw) <- c("FP.COFx", "FP.COFy")
  
  time <- 1:10000
  
# Create extra second at the beginning and at the end
extra1 <- raw[c(1000:1),]
extra2 <- raw[c(30000:29001),]

raw <- rbind.data.frame(extra1, raw, extra2)

# We make this "fake" points because butterworse filter will distort the first and last data points.

# Butterworse filtering
f=1000
raw$'FP.COFx' <- bwfilter(raw$'FP.COFx', f=f, n=4, to=13)
raw$'FP.COFy' <- bwfilter(raw$'FP.COFy', f=f, n=4, to=13)

ROW <- nrow(raw)
raw <- raw[c(1001:(ROW-1000)),] # Removing "fake" points after filter application

  x <- cbind.data.frame(raw$'FP.COFx',raw$'FP.COFy')

  
  #plot gefilterde data
  plot(x, xlim=c(-40,40), ylim=c(-40,40))
  
  pca <- princomp(x)
  
  pcascores <- as.data.frame(pca$scores)
  
  
  #plot getransformeerde en gefilterde data
  
  
  plot(pca$scores[,1], pca$scores[,2], xlim=c(-25,25), ylim=c(-25,25), xlab="AP pathlength (cm)", ylab="ML pathlength (cm)", main=.file)
  
  
  interval <- floor(length(pca$scores[,1])/3)
  
  
  points(pca$scores[,1][1:interval], pca$scores[,2][1:interval], col = "firebrick2")
  
  points(pca$scores[,1][interval:(2*interval)], pca$scores[,2][interval:(2*interval)], col = "darkorange2")
  
  points(pca$scores[,1][(2*interval):(3*interval)], pca$scores[,2][(2*interval):(3*interval)], col = "goldenrod2")
  
  
  
  
  summary(pcascores)
  
  length1 <- 1.96*pca$sdev[1]
  length2 <- 1.96*pca$sdev[2]
  
  
  #oppervlakte berekenen
  A_ellipse <- length1*length2*pi
  
  A_ellipse <- as.numeric(A_ellipse)
  
  draw.ellipse(0,0,a=length1, b=length2)

  
}


setwd("C:\\Research data\\Postural_Control_Github\\scripts\\Check_Raw_Files")
filenames <- Sys.glob("*.dat")  # however you get the list of file
ALLES <- lapply(filenames, ALLESFUNCTIE)

```




